ProductRepairDealerUI/Controllers/CaseController.cs
using Microsoft.AspNetCore.Mvc;
using ProductRepairDataAccess.DataAccess;
using ProductRepairDataAccess.Interfaces;
using ProductRepairDataAccess.Models;
using ProductRepairDataAccess.Models.Entities;
using ProductRepairDataAccess.Models.Enums;

namespace ProductRepairDealerUI.Controllers;

public class CaseController : Controller
{
    private readonly IAccountService _accountService;
    private readonly string _dbConnection;
    private readonly IDataAccessOperations _dataAccess;
    private readonly ICaseDataAccess _caseDataAccess;
    private readonly IItemDataAccess _itemDataAccess;

    public CaseController(
        IAccountService accountService,
        IDataAccessOperations dataAccess, 
        ICaseDataAccess caseDataAccess, 
        IItemDataAccess itemDataAccess)
    {
        _accountService = accountService;
        _dataAccess = dataAccess;
        _caseDataAccess = caseDataAccess;
        _itemDataAccess = itemDataAccess;
    }

    // GET: CaseController
    public async Task<ActionResult> CreateCase()
    {
        string accountId = await _accountService.GetUserAccountIdAsync();

        int caseId = await _caseDataAccess.CreateCaseAsync(
                    accountId,
                    IncidentType.RepairRequest,
                    SalesChannel.Dealer,
                    CaseStatus.Draft);

        Case caseModel = new Case
        {
            CaseId = caseId,
            AccountId = accountId
        };

        return View("ViewCase", caseModel);
    }

    // GET: CaseController
    public async Task<ActionResult> ViewCase(int caseId)
    {
        Case caseModel = await _caseDataAccess.GetCaseModelAsync(caseId);

        return View(caseModel);
    }

    public async Task<ActionResult> NewItem(int caseId)
    {
        Case caseModel = await _caseDataAccess.GetCaseModelAsync(caseId);

        return View(caseModel);
    }

    [HttpPost]
    public async Task<ActionResult> AddItem(NewCase newItem)
    {
        // Process the other fields submitted in the form and update the datasources
        await _itemDataAccess.AddItemToCaseAsync(newItem);

        Case caseModel = await _caseDataAccess.GetCaseModelAsync(newItem.CaseId);

        return View("ViewCase", caseModel);
    }

    public async Task<ActionResult> NewItemIssue(int caseId, Guid ItemId)
    {
        Item itemModel = await _itemDataAccess.GetItemModelAsync(ItemId);

        return View(itemModel);
    }

    [HttpPost]
    public async Task<ActionResult> AddItemIssue(NewItemIssue newItemIssue)
    {
        // Process the other fields submitted in the form and update the datasources
        await _itemDataAccess.AddItemIssueToItemAsync(newItemIssue);

        Case caseModel = await _caseDataAccess.GetCaseModelAsync(newItemIssue.CaseId);

        return View("ViewCase", caseModel);
    }

    [HttpPost]
    public async Task<ActionResult> AddCustomerInformation (Case newCustomerCaseModel)
    {  
        if (Request.Form["ReceiveNotification"] == "on")
        {
            newCustomerCaseModel.ReceiveNotification = true;
        }
        else
        {
            newCustomerCaseModel.ReceiveNotification = false;
        }

        await _caseDataAccess.AddCustomerInformationToCaseAsync(newCustomerCaseModel);

        Case caseModel = await _caseDataAccess.GetCaseModelAsync(newCustomerCaseModel.CaseId);

        return View("ViewCase", caseModel);
    }

    public async Task<ActionResult> RemoveCustomerInformation (int caseId)
    {

        await _caseDataAccess.RemoveCustomerInformationFromCaseAsync(caseId);

        Case caseModel = await _caseDataAccess.GetCaseModelAsync(caseId);

        return View("ViewCase", caseModel);
    }

    public async Task<ActionResult> SubmitCase(int caseId)
    {
        await _caseDataAccess.UpdateCaseStatusAsync(caseId,"Open");

        return View();
    }

    public async Task<ActionResult> SaveDraft(int caseId)
    {
        Case caseModel = await _caseDataAccess.GetCaseModelAsync(caseId);

        return View(caseModel);
    }

    public async Task<ActionResult> DraftCases()
    {
        string accountId = await _accountService.GetUserAccountIdAsync();

        Cases casesModel = new Cases();

        casesModel.CasesList.AddRange(await _caseDataAccess.GetCasesAsync("draft", accountId));

        return View(casesModel);
    }

    public async Task<ActionResult> CreateShipment(int caseId)
    {
        Case caseModel = await _caseDataAccess.GetCaseModelAsync(caseId);

        return View(caseModel);
    }

    public async Task<ActionResult> CancelCase(int caseId)
    {
        await _caseDataAccess.UpdateCaseStatusAsync(caseId, "Canceled");

        Case caseModel = await _caseDataAccess.GetCaseModelAsync(caseId);

        return View();
    }
}

ProductRepairDealerUI/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Product Repair - Dealer</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductRepairDealerUI.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Product Repair</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Case" asp-action="CreateCase">Create Case</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Case" asp-action="DraftCases">Drafts</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Case" asp-action="Shipments">Shipments</a>
                            </li>
                        }
                        
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ProductRepairDealer
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>